project_id = "kavlzghtpdfvyjxwsiuj"

[functions.create-payment]
verify_jwt = false

[functions.create-subscription]
verify_jwt = false

[functions.asaas-webhook]
verify_jwt = false

[functions.generate-disc-report]
verify_jwt = false
